### ISSUE TITLE
API for declaring chapters

### ISSUE THREAD

**Issue by ndelangen** [sm-react/storybook-chapters#1]
In your readme you've documented this as the API for adding chapters:

```
// stories.js:

storiesOf('React App', module)
    .chapter('Left panel')
        .add('Button 1', fn(1))
        .add('Button 2', fn(2))
        .chapter('Bottom Panel')
            .add('Input 3', fn(3))
            .add('Input 4', fn(4))
            .endOfChapter()
        .chapter('Header Panel')
            .add('Input 5', fn(5))
            .add('Input 6', fn(6))
            .endOfChapter()
        .endOfChapter()
    .chapter('Right panel')
        .add('Button 7', fn(7))
        .add('Button 8', fn(8))
        .endOfChapter()
```

I wonder how much effort it would take to change this into:
```
// stories.js:

storiesOf('React App', module)
    .chapter('Left panel', chapter => chapter
        .add('Button 1', fn(1))
        .add('Button 2', fn(2))
        .chapter('Bottom Panel', chapter => chapter
            .add('Input 3', fn(3))
            .add('Input 4', fn(4))
        )
    )
    .chapter('Header Panel', chapter => chapter
        .add('Input 5', fn(5))
        .add('Input 6', fn(6))
    )
    .chapter('Right panel' chapter => chapter
        .add('Button 7', fn(7))
        .add('Button 8', fn(8))
    )
```

No more need for `.endOfChapter()` and code indenting-wise it's more correct.

**Comment by UsulPro** [comment]
Hi, @ndelangen!
Thank you for the great idea!

I think adding these API should not be too difficult. So it looks like it's worth doing it in the next release.

Up to this point, maybe someone else has ideas about this?

/сс @hadfieldn

**Comment by hadfieldn** [comment]
I like this idea but it might make it more difficult to implement storybook-filepath-chapters, since the content of the chapter would have to be assembled prior to adding the chapter. I suppose the ideal for me would be if you could support both APIs. :-)

**Comment by ndelangen** [comment]
Very interesting plugin! I did not know that existed.

Can you explain in a bit more detail why such an API would mean it'd be impossible for you to implement on? 

Is static generation of this tree impossible? What is the reason the chapters/stories are added each level separate?.

**Comment by hadfieldn** [comment]
@ndelangen There may well be a better way to have implemented it, but basically I needed each of my calls to `storiesOf` in each of my stories files to create a new chapter inside the chapter corresponding to their folder in the filesystem. In order to determine which folder a story is in, I replaced the Storybook loader so that I could inspect the path of each story file found by the npm require context. The loader creates subchapters for each folder it encounters. I made my own `storiesOf` function, which has to be imported instead of the original function with the same name. Instead of adding stories to the main root story as the original function does, it adds them to the current chapter being managed by the loader. Essentially the system is a state machine, opening and closing chapters as new folders and sets of stories are encountered. It doesn't require any changes to the story files except for changing the `storiesOf` import to use the version from `storybook-filepath-chapters`. This was an important design goal for me -- I wanted existing story files to work with minimal code changes.

With the proposed API change, constructing storybook chapters from filepaths would have to change from a state machine that can process story files as they are encountered sequentially to a bottom-up model that requires subchapters to have been defined at the time parent chapters are created. 

I might be able to support this by making my custom storiesOf function register a reference to each chapter object it creates and then, after the files have been loaded, use this registry to assemble chapters hierarchically from the bottom up. Or maybe there's a simpler way that I'm just overlooking.

At any rate, I don't think this project should be overly concerned with the way it impacts storybook-filepath-chapters, but I do think it would require a complete rewrite and it may take a while for me to find the time to do it. From the perspective of a developer creating a chapter tree directly, the proposed API certainly would have the advantage of removing the need to pair each chapter opening with a corresponding closing call.

**Comment by UsulPro** [comment]
@ndelangen @hadfieldn It seems to me that both approaches make sense.

And I don't think their implementation may conflict with each other. So how do you think is it good idea to have the both approaches? 
In that case I will add `addChapter` wich implements @ndelangen's offer and keep `chapter`/`endOfChapter` to provide flexible API for addon developers

**Comment by hadfieldn** [comment]
That would be great for me.

I could actually see some advantages to reimplementing filepath chapters
with a two-pass method that first scans the file system and then uses the
new API to build the chapters.. so eventually I might give it a shot. But I
dont think it would hurt to make both methods available regardless.

**Comment by UsulPro** [comment]
Thanks guys for this discussion and ideas!

[Now](https://github.com/sm-react/storybook-chapters/releases/tag/0.3.0) it's possible to use both API and make any combinations of them!
